name: Terraform deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

defaults:
  run:
    working-directory: ./infra

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: eu-west-1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        if: success()
        run: terraform fmt

      - name: Terraform init
        if: success()
        run: terraform init

      - name: Terraform plan
        if: success()
        run: terraform plan

      - name: Terraform apply
        if: success()
        run: terraform apply -auto-aprove
